from pathlib import Path
import json
import pandas as pd
import streamlit as st
from components import metric_cards, alert_card, qaoa_status, emergency_status, signal_table, explanation_card
from network_view import render_network
from charts import render_metrics
from scenarios.location_presets import list_locations
from ai.traffic_state import create_state

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/"outputs"
st.set_page_config(page_title="Quantum-Enhanced Adaptive Urban Traffic Optimization", layout="wide")
st.title("Quantum-Enhanced Adaptive Urban Traffic Optimization")
location=st.sidebar.selectbox("LOCATION", list_locations(), index=0)
st.sidebar.caption("Simulation preset — not live traffic.")

metrics_path=OUT/"metrics.csv"
df=pd.read_csv(metrics_path) if metrics_path.exists() else pd.DataFrame()
results=json.loads((OUT/"scenario_results.json").read_text(encoding="utf-8")) if (OUT/"scenario_results.json").exists() else []
alerts=json.loads((OUT/"alerts.json").read_text(encoding="utf-8")) if (OUT/"alerts.json").exists() else []

st.header("NETWORK")
states={}
if not df.empty:
    last=df.iloc[-1]
    base=[28,36,42,30]
    queues=[9,14,18,10]
    for i,j in enumerate(["J1","J2","J3","J4"]):
        states[j]={"vehicles":base[i],"queue":queues[i],"waiting":last["average_waiting_time"],
                    "signal":results[-1]["plans"].get(j,"PLAN_2") if results else "PLAN_2",
                    "optimized_plan":results[-1]["plans"].get(j,"PLAN_2") if results else "PLAN_2",
                    "congestion":"HIGH" if queues[i]/50>.3 else "MEDIUM"}
render_network(states)
for j,s in states.items():
    st.write(j, s)

st.header("PREDICTION")
if results:
    st.write("30 sec / 60 sec / 120 sec / 300 sec predictions are generated by the weighted moving-average + trend predictor during the demo.")
else:
    st.info("Run `python run_demo.py` first.")

st.header("TRAFFIC SHOCK")
if results:
    r=results[-1]
    st.json(r["shock"])
else: st.info("No scenario results yet.")

st.header("QUBO")
st.write("12 variables · 4 junctions · 3 plans/junction · exactly-one constraint per junction.")
st.write("Objective: waiting, queue, throughput, congestion, spillback, emergency delay, fuel, CO2, signal-change penalty.")

st.header("QAOA")
if results:
    qaoa_status(results[-1]["qaoa"])
    signal_table(results[-1]["plans"])
else: st.info("No QAOA result yet.")

st.header("WHY DID SIGNAL CHANGE?")
if results:
    st.write("Explanation is generated from the scenario event and optimization inputs; it does not invent a performance improvement.")
    st.write(f"Current event: {results[-1]['event']}. Selected plans: {results[-1]['plans']}.")

st.header("EMERGENCY")
for r in results:
    if r["event"]=="AMBULANCE":
        emergency_status(r["emergency"])
        st.write("AMB01 · J1 → J2 → J3 → J4")
        break

st.header("ALERTS")
for a in alerts[-5:]:
    alert_card(a)

st.header("METRICS")
render_metrics(df)

st.header("CLASSICAL VS QAOA")
st.write("The project records actual measured execution information. No improvement percentage is fabricated; if QAOA is a fallback or performs differently, the recorded status is shown.")
